language: ruby
rvm:
- 2.2
deploy:
  api_key:
    secure: qZnIE7KSU1yCsNV83wUQPccjxy7BgmHomnxvE5Z2sb11J+mXMWXw/SDwKEFZy0TbHbKbrkir5U8xAqL263ljJ1tAEjm77F8V25pGFZrcThnfTNSNcTLI+LrNpdnh7NZ9NKGUzUSr5ktveM85bMk/bklq+f71Ov9ZM9i93eoID2WqaX4l+QQ31E1iGzGRRQO0SZv1ebRDPBCL6wCY1blDcLVKm/YSXqep93PIMfCb/7wDBvS0PtLG2vk0YqGGIlEvs0Hwk+c2O4eQQl89og2MZZL5zb5sciOca4VG66/V/AdeizJg1qYtNG9xZ8SDqNiN/7ah0hvIoMxRxrHbg6J+orx/sDEFxgXl/zVSzqjQaijwwdh4O8+UvMrqzyf7KAITuO9cuR7qCCcCSJEQ5519WNInvY/7jJFJjqd4u2p40lTttdvSoIMDiZDth4IzRv29qFiZyVccr4aMD/VHnkITjwkaFd4OcwHqtOxwAHohAvjWMZksWQV0wkwzyK34kxf/HFnDziEt+KFjhKZXfn1dvZcDFWwQ1P2w/1BX+GgiYM5UGbEiQwKAiEOv5XuHbNd3Pf/HT5mnc8OZ65jCTPH1gci6SoX2KOj7XjoO3acb9xNXo9+94CCAyA96IJ46iIXgnPSZfr8g8glywezO2i0pdloPV8PtgK0fepOds7qBcy8=
